version: '3.8'

services:
  db:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: carbox
      MONGO_INITDB_ROOT_USERNAME: carbox
      MONGO_INITDB_ROOT_PASSWORD: mySecretPassword
    volumes:
      - ./mongo-init:/docker-entrypoint-initdb.d

  restapi:
    build: .
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://carbox:mySecretPassword@db:27017/carbox?authSource=admin
    depends_on:
      - db
    ports:
      - "8080:8080"
